type: object
properties:
  href:
    maxLength: 1024
    minLength: 1
    type: string
    title: Environment Bill of Materials Product Console Href
required: []
title: Environment Bill of Materials Product Console
