type: object
properties:
  numberOfAadhaar:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Aadhaar
  numberOfAccountOwnership:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Account Ownership
  numberOfDataVerificationGroup1:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Data Verification Group 1
  numberOfDataVerificationGroup2:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Data Verification Group 2
  numberOfDataVerificationGroup3:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Data Verification Group 3
  numberOfDataVerificationGroup4:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Data Verification Group 4
  numberOfDataVerificationGroup5:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Data Verification Group 5
  numberOfDataVerifications:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Data Verifications
  numberOfDeviceReputationScoring:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Device Reputation Scoring
  numberOfGlobalWatchlist:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Global Watchlist
  numberOfLiveAgent:
    type: integer
    format: int64
    title: Environment License Quantities Number Of Live Agent
  rlgAnalyticsRpm:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgAppRegRpm:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgAuditRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgAuthnRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgAuthnStartRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgAuthzBulkRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgAuthzRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgCatchAllRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgConfigRpm:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgCredRpm:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgDirAccessRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgDirBulkRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgDirFixedRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgDirWriteRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgDvFlowCallbackRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgDvFlowExecRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgDvFlowStartRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgMfaFixedRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgMfaPollingRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgMfaRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgPrivilegeRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgRiskEvalsRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgTokenCheckRps:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
  rlgVerifyRpm:
    $ref: >-
      ./com.pingidentity.pingone.orgmgt.environments.capabilities.api.model.ApiLimit.yaml
title: Environment License Quantities
