type: object
additionalProperties: true
properties:
  csp:
    type: string
    title: DaVinci Flow Settings Request Csp
  css:
    type: string
    title: DaVinci Flow Settings Request Css
  cssLinks:
    type: array
    items:
      type: string
      title: DaVinci Flow Settings Request Css Link
    title: DaVinci Flow Settings Request Css Links
  customErrorScreenBrandLogoUrl:
    type: string
    title: DaVinci Flow Settings Request Custom Error Screen Brand Logo Url
  customErrorShowFooter:
    oneOf:
      - type: boolean
        title: DaVinci Flow Settings Request Custom Error Show Footer Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: DaVinci Flow Settings Request Custom Error Show Footer Choice 2
    title: DaVinci Flow Settings Request Custom Error Show Footer
  customFaviconLink:
    type: string
    title: DaVinci Flow Settings Request Custom Favicon Link
  customLogoURLSelection:
    type: integer
    title: DaVinci Flow Settings Request Custom Logo URL Selection
  customTitle:
    type: string
    title: DaVinci Flow Settings Request Custom Title
  defaultErrorScreenBrandLogo:
    oneOf:
      - type: boolean
        title: DaVinci Flow Settings Request Default Error Screen Brand Logo Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: DaVinci Flow Settings Request Default Error Screen Brand Logo Choice 2
    title: DaVinci Flow Settings Request Default Error Screen Brand Logo
  flowHttpTimeoutInSeconds:
    type: integer
    title: DaVinci Flow Settings Request Flow Http Timeout In Seconds
  flowTimeoutInSeconds:
    type: integer
    title: DaVinci Flow Settings Request Flow Timeout In Seconds
  intermediateLoadingScreenCSS:
    oneOf:
      - type: string
        title: DaVinci Flow Settings Request Intermediate Loading Screen CSS Choice 1
      - type: object
        title: DaVinci Flow Settings Request Intermediate Loading Screen CSS Choice 2
    title: DaVinci Flow Settings Request Intermediate Loading Screen CSS
  intermediateLoadingScreenHTML:
    oneOf:
      - type: string
        title: >-
          DaVinci Flow Settings Request Intermediate Loading Screen HTML Choice
          1
      - type: object
        title: >-
          DaVinci Flow Settings Request Intermediate Loading Screen HTML Choice
          2
    title: DaVinci Flow Settings Request Intermediate Loading Screen HTML
  jsCustomFlowPlayer:
    type: string
    title: DaVinci Flow Settings Request Js Custom Flow Player
  jsLinks:
    type: array
    items:
      type: object
      properties:
        label:
          type: string
          minLength: 1
          title: DaVinci Flow Settings Request Js Link Label
        value:
          type: string
          minLength: 1
          title: DaVinci Flow Settings Request Js Link Value
        defer:
          oneOf:
            - type: boolean
              title: DaVinci Flow Settings Request Js Link Defer Choice 1
            - type: string
              enum:
                - 'false'
                - 'true'
              title: DaVinci Flow Settings Request Js Link Defer Choice 2
          title: DaVinci Flow Settings Request Js Link Defer
        crossorigin:
          type: string
          minLength: 1
          title: DaVinci Flow Settings Request Js Link Crossorigin
        integrity:
          type: string
          minLength: 1
          title: DaVinci Flow Settings Request Js Link Integrity
        referrerpolicy:
          type: string
          minLength: 1
          title: DaVinci Flow Settings Request Js Link Referrerpolicy
        type:
          type: string
          minLength: 1
          title: DaVinci Flow Settings Request Js Link Type
      required:
        - label
        - value
        - defer
        - crossorigin
        - integrity
        - referrerpolicy
        - type
      title: DaVinci Flow Settings Request Js Link
    title: DaVinci Flow Settings Request Js Links
  logLevel:
    type: integer
    minimum: 1
    maximum: 4
    title: DaVinci Flow Settings Request Log Level
  requireAuthenticationToInitiate:
    oneOf:
      - type: boolean
        title: >-
          DaVinci Flow Settings Request Require Authentication To Initiate
          Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: >-
          DaVinci Flow Settings Request Require Authentication To Initiate
          Choice 2
    title: DaVinci Flow Settings Request Require Authentication To Initiate
  scrubSensitiveInfo:
    oneOf:
      - type: boolean
        title: DaVinci Flow Settings Request Scrub Sensitive Info Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: DaVinci Flow Settings Request Scrub Sensitive Info Choice 2
    title: DaVinci Flow Settings Request Scrub Sensitive Info
  sensitiveInfoFields:
    type: array
    items:
      type: string
      title: DaVinci Flow Settings Request Sensitive Info Field
    title: DaVinci Flow Settings Request Sensitive Info Fields
  useCSP:
    oneOf:
      - type: boolean
        title: DaVinci Flow Settings Request Use CSP Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: DaVinci Flow Settings Request Use CSP Choice 2
    title: DaVinci Flow Settings Request Use CSP
  useCustomCSS:
    oneOf:
      - type: boolean
        title: DaVinci Flow Settings Request Use Custom CSS Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: DaVinci Flow Settings Request Use Custom CSS Choice 2
    title: DaVinci Flow Settings Request Use Custom CSS
  useCustomFlowPlayer:
    oneOf:
      - type: boolean
        title: DaVinci Flow Settings Request Use Custom Flow Player Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: DaVinci Flow Settings Request Use Custom Flow Player Choice 2
    title: DaVinci Flow Settings Request Use Custom Flow Player
  useCustomScript:
    oneOf:
      - type: boolean
        title: DaVinci Flow Settings Request Use Custom Script Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: DaVinci Flow Settings Request Use Custom Script Choice 2
    title: DaVinci Flow Settings Request Use Custom Script
  useIntermediateLoadingScreen:
    oneOf:
      - type: boolean
        title: DaVinci Flow Settings Request Use Intermediate Loading Screen Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: DaVinci Flow Settings Request Use Intermediate Loading Screen Choice 2
    title: DaVinci Flow Settings Request Use Intermediate Loading Screen
  validateOnSave:
    oneOf:
      - type: boolean
        title: DaVinci Flow Settings Request Validate On Save Choice 1
      - type: string
        enum:
          - 'false'
          - 'true'
        title: DaVinci Flow Settings Request Validate On Save Choice 2
    title: DaVinci Flow Settings Request Validate On Save
title: DaVinci Flow Settings Request
