get:
  operationId: getEnvironmentById
  parameters:
    - $ref: >-
        ../components/parameters/com.pingidentity.path.environments.environmentID.yaml
    - name: expand
      in: query
      schema:
        type: string
    - $ref: ../components/parameters/com.pingidentity.header.ExternalSessionID.yaml
    - $ref: >-
        ../components/parameters/com.pingidentity.header.ExternalTransactionID.yaml
  responses:
    '200':
      description: Successful operation.
      content:
        application/hal+json:
          schema:
            $ref: >-
              ../components/schemas/com.pingidentity.pingone.orgmgt.environments.data.Environment.yaml
        application/json:
          schema:
            $ref: >-
              ../components/schemas/com.pingidentity.pingone.orgmgt.environments.data.Environment.yaml
    '400':
      $ref: ../components/responses/http.400.BadRequest.yaml
    '401':
      $ref: ../components/responses/http.401.Unauthorized.yaml
    '403':
      $ref: ../components/responses/http.403.Forbidden.yaml
    '404':
      $ref: ../components/responses/http.404.NotFound.yaml
    '429':
      $ref: ../components/responses/http.429.TooManyRequests.yaml
    '500':
      $ref: ../components/responses/http.500.InternalServerError.yaml
    '502':
      $ref: ../components/responses/http.502.BadGateway.yaml
    '503':
      $ref: ../components/responses/http.503.ServiceUnavailable.yaml
  x-permission: orgmgt:read:environment
  tags:
    - Environments
put:
  operationId: replaceEnvironmentById
  parameters:
    - $ref: >-
        ../components/parameters/com.pingidentity.path.environments.environmentID.yaml
    - $ref: ../components/parameters/com.pingidentity.header.ExternalSessionID.yaml
    - $ref: >-
        ../components/parameters/com.pingidentity.header.ExternalTransactionID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: >-
            ../components/schemas/com.pingidentity.pingone.orgmgt.environments.data.ReplaceEnvironment.yaml
    required: true
  responses:
    '200':
      description: Successful operation.
      content:
        application/hal+json:
          schema:
            $ref: >-
              ../components/schemas/com.pingidentity.pingone.orgmgt.environments.data.Environment.yaml
        application/json:
          schema:
            $ref: >-
              ../components/schemas/com.pingidentity.pingone.orgmgt.environments.data.Environment.yaml
    '201':
      description: Successfully created.
      content:
        application/hal+json:
          schema:
            $ref: >-
              ../components/schemas/com.pingidentity.pingone.orgmgt.environments.data.Environment.yaml
        application/json:
          schema:
            $ref: >-
              ../components/schemas/com.pingidentity.pingone.orgmgt.environments.data.Environment.yaml
    '400':
      $ref: ../components/responses/http.400.BadRequest.yaml
    '401':
      $ref: ../components/responses/http.401.Unauthorized.yaml
    '403':
      $ref: ../components/responses/http.403.Forbidden.P14C63085.yaml
    '404':
      $ref: ../components/responses/http.404.NotFound.DOCS8830.yaml
    '429':
      $ref: ../components/responses/http.429.TooManyRequests.yaml
    '500':
      $ref: ../components/responses/http.500.InternalServerError.yaml
    '502':
      $ref: ../components/responses/http.502.BadGateway.yaml
    '503':
      $ref: ../components/responses/http.503.ServiceUnavailable.yaml
  x-permission: orgmgt:update:environment
  tags:
    - Environments
delete:
  operationId: deleteEnvironmentById
  parameters:
    - $ref: >-
        ../components/parameters/com.pingidentity.path.environments.environmentID.yaml
    - $ref: ../components/parameters/com.pingidentity.header.ExternalSessionID.yaml
    - $ref: >-
        ../components/parameters/com.pingidentity.header.ExternalTransactionID.yaml
  responses:
    '204':
      description: Successfully removed. No content.
    '400':
      $ref: ../components/responses/http.400.BadRequest.yaml
    '401':
      $ref: ../components/responses/http.401.Unauthorized.yaml
    '403':
      $ref: ../components/responses/http.403.Forbidden.P14C63085.yaml
    '404':
      $ref: ../components/responses/http.404.NotFound.DOCS8830.yaml
    '429':
      $ref: ../components/responses/http.429.TooManyRequests.yaml
    '500':
      $ref: ../components/responses/http.500.InternalServerError.yaml
    '502':
      $ref: ../components/responses/http.502.BadGateway.yaml
    '503':
      $ref: ../components/responses/http.503.ServiceUnavailable.yaml
  x-permission: orgmgt:delete:environment
  tags:
    - Environments
